const Backend = (() => {
  let mode = "local", db = null;
  function waitForAuth(){return new Promise(resolve=>{if(typeof firebase==="undefined"||!firebase.auth)return resolve(null);const existing=firebase.auth().currentUser;if(existing)return resolve(existing);let settled=false;const unsub=firebase.auth().onAuthStateChanged(u=>{if(settled)return;settled=true;unsub();resolve(u||null)});setTimeout(()=>{if(!settled){settled=true;unsub();resolve(firebase.auth().currentUser||null)}},5000)})}
  async function init(){mode="local";db=null;if(typeof firebase==="undefined"||typeof firebaseConfig==="undefined"||!firebaseConfig?.apiKey||firebaseConfig.apiKey.startsWith("PASTE_"))return mode;try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);const user=await waitForAuth();if(!user||!user.email)throw new Error("No authenticated FiveZone user.");await user.getIdToken(true);db=firebase.firestore();mode="cloud"}catch(e){console.error("Firebase init failed",e);mode="local"}return mode}
  function currentUser(){return firebase?.auth?.().currentUser||null}
  function currentFriend(){const u=currentUser();return FRIENDS.find(f=>f.email.toLowerCase()===(u?.email||"").toLowerCase())||null}
  function sendMessage(name,text){const u=currentUser(),f=currentFriend();if(mode!=="cloud"||!u||!f||f.name!==name)return Promise.reject(new Error("Not connected or invalid FiveZone user."));const clean=String(text||"").trim().slice(0,2000);if(!clean)return Promise.resolve();return db.collection("messages").add({uid:u.uid,email:u.email,name:f.name,text:clean,ts:Date.now()})}
  function onMessages(cb,err){if(mode==="cloud")return db.collection("messages").orderBy("ts","asc").limit(200).onSnapshot(s=>cb(s.docs.map(d=>d.data())),e=>{console.error("Messages listener failed",e);if(err)err(e)});cb([]);return()=>{}}
  function setStatus(name,status){const u=currentUser(),f=currentFriend();if(mode!=="cloud"||!u||!f||f.name!==name)return Promise.reject(new Error("Invalid FiveZone user."));if(!["Available","Busy","Sleeping","Away"].includes(status))return Promise.reject(new Error("Invalid status."));return db.collection("statuses").doc(f.name).set({uid:u.uid,email:u.email,status,ts:Date.now()},{merge:true})}
  function onStatuses(cb,err){if(mode==="cloud")return db.collection("statuses").onSnapshot(s=>{const out={};s.forEach(d=>out[d.id]=d.data());cb(out)},e=>{console.error("Status listener failed",e);if(err)err(e)});cb({});return()=>{}}
  function setNextCall(iso){const u=currentUser();if(mode!=="cloud"||!u)return Promise.reject(new Error("Not connected to Firebase."));return db.collection("meta").doc("next_call").set({when:iso,uid:u.uid,email:u.email})}
  function onNextCall(cb,err){if(mode==="cloud")return db.collection("meta").doc("next_call").onSnapshot(d=>cb(d.exists?d.data().when:null),e=>{console.error("Next call listener failed",e);if(err)err(e)});cb(null);return()=>{}}
  function heartbeat(){const u=currentUser(),f=currentFriend();if(mode!=="cloud"||!u||!f)return Promise.resolve();return db.collection("presence").doc(f.name).set({uid:u.uid,email:u.email,name:f.name,lastSeen:Date.now()},{merge:true})}
  function onPresence(cb,err){if(mode==="cloud")return db.collection("presence").onSnapshot(s=>{const out={};s.forEach(d=>out[d.id]=d.data());cb(out)},e=>{if(err)err(e)});cb({});return()=>{}}
  function saveGameScore(game,score){const u=currentUser(),f=currentFriend();if(mode!=="cloud"||!u||!f)return Promise.reject(new Error("Not connected."));return db.collection("game_scores").doc(`${game}_${f.name}`).set({game,name:f.name,uid:u.uid,score:Number(score)||0,ts:Date.now()},{merge:true})}
  function getGameScores(){if(mode!=="cloud")return Promise.resolve([]);return db.collection("game_scores").get().then(s=>s.docs.map(d=>d.data()))}
  function saveTTT(state){const u=currentUser(),f=currentFriend();if(mode!=="cloud"||!u||!f)return Promise.reject(new Error("Not connected."));return db.collection("games").doc("ttt").set({...state,updatedBy:f.name,ts:Date.now()},{merge:false})}
  function getTTT(){if(mode!=="cloud")return Promise.resolve(null);return db.collection("games").doc("ttt").get().then(d=>d.exists?d.data():null)}
  function watchTTT(cb){if(mode==="cloud")return db.collection("games").doc("ttt").onSnapshot(d=>cb(d.exists?d.data():null));cb(null);return()=>{}}
  return{init,mode:()=>mode,currentUser,currentFriend,sendMessage,onMessages,setStatus,onStatuses,setNextCall,onNextCall,heartbeat,onPresence,saveGameScore,getGameScores,saveTTT,getTTT,watchTTT};
})();